SELECT YEAR(b.SALES_DATE) YEAR, MONTH(b.SALES_DATE) MONTH, a.GENDER, COUNT(DISTINCT a.USER_ID) USERS
FROM USER_INFO a
JOIN ONLINE_SALE b ON
    a.USER_ID = b.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE), a.GENDER
ORDER BY YEAR, MONTH, GENDER;