SELECT MONTH(a.START_DATE) MONTH, a.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
WHERE a.CAR_ID IN (SELECT b.CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY b
                  WHERE DATE_FORMAT(b.START_DATE, "%Y-%m") BETWEEN '2022-08' AND '2022-10'
                  GROUP BY b.CAR_ID
                  HAVING COUNT(*) >= 5)
AND DATE_FORMAT(a.START_DATE, "%Y-%m") BETWEEN '2022-08' AND '2022-10'

GROUP BY MONTH, a.CAR_ID
HAVING COUNT(*) != 0
ORDER BY MONTH, CAR_ID DESC