WITH RECURSIVE GET_HOUR (HOUR) AS (
    SELECT 0
    UNION ALL
    SELECT HOUR+1
    FROM GET_HOUR
    WHERE HOUR < 23)


SELECT HOUR, IFNULL(COUNT(ANIMAL_ID), '0') COUNT
FROM GET_HOUR G
LEFT OUTER JOIN ANIMAL_OUTS A ON 
    G.HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR;